//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCommittee.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyHedear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyHedear()
        {
            this.SurveyDetails = new HashSet<SurveyDetails>();
        }
    
        public long SurveyHedearId { get; set; }
        public string Subject { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CountAnswers { get; set; }
        public bool Status { get; set; }
        public int BuildingId { get; set; }
    
        public virtual building_tbl building_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyDetails> SurveyDetails { get; set; }
    }
}
