//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCommittee.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vote_tbl
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> survey_id { get; set; }
        public Nullable<int> voting { get; set; }
    
        public virtual survey_tbl survey_tbl { get; set; }
        public virtual user_tbl user_tbl { get; set; }
    }
}
